version: '3'

services:
  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
      - ./.next:/app/.next
    environment:
      - NODE_ENV=development
    restart: unless-stopped
